apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: reearth.engineering
  namespace: eukarya-inc
  description: https://reearth.engineering
  annotations:
    github.com/project-slug: eukarya-inc/reearth.engineering
  links:
    - url: https://github.com/eukarya-inc/reearth.engineering
      title: GitHub
      icon: github
    - url: https://dash.cloudflare.com/59c9ce6fe028ec5615ca40f8ab44ad45/pages/view/reearth-engineering
      title: Website
      icon: web
  tags:
    - astro
spec:
  type: service
  lifecycle: experimental
  owner: eukarya-inc/sre
